export const ACTION_TYPES = {
  LOADING: 'LOADING',
  GET_MOVIES: 'GET_MOVIES',
  RECEIVE_MOVIES: 'RECEIVE_MOVIES',
  RECEIVE_GENRES: 'RECEIVE_GENRES',
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
  RESET_MOVIES: 'RESET_MOVIES',
  SET_SELECTED_GENRE: 'SET_SELECTED_GENRE',
};
